name: Run deps bot
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
env:
  RENOVATE_VERSION: 43.177.9 # renovate: datasource=github-releases depName=renovatebot/renovate
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Generate app token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: app-token
        with:
          app-id: ${{ vars.INFRASTRUCTURE_BOT_APP_ID }}
          private-key: ${{ secrets.INFRASTRUCTURE_BOT_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@693b9ef15eec82123529a37c782242f091365961 # v46.1.14
        with:
          renovate-version: ${{ env.RENOVATE_VERSION }}
          configurationFile: config.js
          token: ${{ steps.app-token.outputs.token }}
        env:
          RENOVATE_AUTODISCOVER: 'true'
